using Statistics

team_wins = Dict("Hawks" => 46, "Celtics" => 56, "Nets" => 20, "Hornets" => 44, "Bulls" => 31, "Cavaliers" => 52, "Mavericks" => 31, "Nuggets" => 54, "Pistons" => 60, "Warriors" => 36, "Rockets" => 52, "Pacers" => 19, "Lakers" => 53, "Clippers" => 42, "Grizzlies" => 25, "Heat" => 43, "Bucks" => 32, "Timberwolves" => 49, "Pelicans" => 26, "Knicks" => 53, "Thunder" => 64, "Magic" => 45, "76ers" => 45, "Suns" => 45, "Trail Blazers" => 42, "Kings" => 22, "Spurs" => 62, "Raptors" => 46, "Jazz" => 22, "Wizards" => 17)

avg_g_played = Dict("Hawks" => 59, "Celtics" => 68, "Nets" => 56, "Hornets" => 58, "Bulls" => 51, "Cavaliers" => 55, "Mavericks" => 60, "Nuggets" => 60, "Pistons" => 62, "Warriors" => 58, "Rockets" => 62, "Pacers" => 50, "Clippers" => 58, "Lakers" => 58, "Grizzlies" => 49, "Heat" => 60, "Bucks" => 56, "Timberwolves" => 66, "Pelicans" => 60, "Knicks" => 63, "Thunder" => 56, "Magic" => 58, "76ers" => 59, "Suns"=> 59, "Trail Blazers" => 56, "Kings" => 54, "Spurs" => 65, "Raptors" => 65, "Jazz" => 54, "Wizards" => 53)
avg_mins_played_per_game_per_player = Dict("Hawks" => 23.5, "Celtics" => 23.5, "Nets" => 22.9, "Hornets" => 21.1, "Bulls" => 22.2, "Cavaliers" => 21.9, "Mavericks" => 22.0, "Nuggets" => 24.6, "Pistons" => 20.9, "Warriors" => 22.1, "Rockets" => 22.4, "Pacers" => 20.9, "Clippers" => 22.2, "Lakers" => 22.4, "Grizzlies" => 22.9, "Heat" => 22.5, "Bucks" => 21.4, "Timberwolves" => 23.3, "Pelicans" => 23.5, "Knicks" => 22.1, "Thunder" => 21.0, "Magic" => 20.7, "76ers" => 24.4, "Suns" => 22.0, "Trail Blazers" => 21.5, "Kings" => 24.0, "Spurs" => 21.1, "Raptors" => 22.0, "Jazz" => 24.3, "Wizards" => 22.8)
avg_fgs_made_per_game_per_player = Dict("Hawks" => 4.3, "Celtics" => 4.2, "Nets" => 3.5, "Hornets" => 3.5, "Bulls" => 3.9, "Cavaliers" => 3.9, "Mavericks" => 3.7, "Nuggets" => 4.4, "Pistons" => 3.8, "Warriors" => 3.8, "Rockets" => 3.8, "Pacers" => 3.5, "Clippers" => 3.8, "Lakers" => 4.0, "Grizzlies" => 3.9, "Heat" => 4.1, "Bucks" => 3.8, "Timberwolves" => 4.2, "Pelicans" => 4.0, "Knicks" => 3.9, "Thunder" => 3.8, "Magic" => 3.5, "76ers" => 4.4, "Suns" => 3.9, "Trail Blazers" => 3.7, "Kings" => 4.1, "Spurs" => 3.8, "Raptors" => 3.9, "Jazz" => 4.5, "Wizards" => 4.1)
avg_fgs_attempted_per_game_per_player = Dict("Hawks" => 8.9, "Celtics" => 8.8, "Nets" => 8.1, "Hornets" => 7.7, "Bulls" => 8.2, "Cavaliers" => 8.0, "Mavericks" => 7.9, "Nuggets" => 8.8, "Pistons" => 7.9, "Warriors" => 8.3, "Rockets" => 8.0, "Pacers" => 7.6, "Clippers" => 7.7, "Lakers" => 8.1, "Grizzlies" => 8.4, "Heat" => 8.8, "Bucks" => 7.8, "Timberwolves" => 8.6, "Pelicans" => 8.8, "Knicks" => 8.1, "Thunder" => 7.7, "Magic" => 7.7, "76ers" => 9.4, "Suns" => 8.7, "Trail Blazers" => 8.2, "Kings" => 8.9, "Spurs" => 8.0, "Raptors" => 7.9, "Jazz" => 9.6, "Wizards" => 8.8)
avg_fg_pct_per_player = Dict("Hawks" => 0.476, "Celtics" => 0.474, "Nets" => 0.439, "Hornets" => 0.461, "Bulls" => 0.470, "Cavaliers" => 0.488, "Mavericks" => 0.470, "Nuggets" => 0.501, "Pistons" => 0.482, "Warriors" => 0.463, "Rockets" => 0.476, "Pacers" => 0.458, "Clippers" => 0.492, "Lakers" => 0.499, "Grizzlies" => 0.462, "Heat" => 0.467, "Bucks" => 0.490, "Timberwolves" => 0.482, "Pelicans" => 0.460, "Knicks" => 0.478, "Thunder" => 0.487, "Magic" => 0.463, "76ers" => 0.464, "Suns" => 0.451, "Trail Blazers" => 0.454, "Kings" => 0.467, "Spurs" => 0.482, "Raptors" => 0.492, "Jazz" => 0.465, "Wizards" => 0.467)
avg_3ps_made_per_game_per_player = Dict("Hawks" => 1.5, "Celtics" => 1.5, "Nets" => 1.2, "Hornets" => 1.4, "Bulls" => 1.2, "Cavaliers" => 1.3, "Mavericks" => 1.0, "Nuggets" => 1.4, "Pistons" => 1.0, "Warriors" => 1.5, "Rockets" => 1.0, "Pacers" => 1.1, "Clippers" => 1.1, "Lakers" => 1.1, "Grizzlies" => 1.3, "Heat" => 1.3, "Bucks" => 1.2, "Timberwolves" => 1.4, "Pelicans" => 1.2, "Knicks" => 1.3, "Thunder" => 1.1, "Magic" => 1.0, "76ers" => 1.3, "Suns" => 1.4, "Trail Blazers" => 1.3, "Kings" => 1.1, "Spurs" => 1.2, "Raptors" => 1.0, "Jazz" => 1.4, "Wizards" => 1.2)
avg_3ps_attempted_per_game_per_player = Dict("Hawks" => 4.0, "Celtics" => 4.1, "Nets" => 3.7, "Hornets" => 3.8, "Bulls" => 3.5, "Cavaliers" => 3.6, "Mavericks" => 2.8, "Nuggets" => 3.5, "Pistons" => 2.8, "Warriors" => 4.2, "Rockets" => 2.8, "Pacers" => 3.1, "Clippers" => 3.0, "Lakers" => 3.2, "Grizzlies" => 3.7, "Heat" => 3.7, "Bucks" => 3.2, "Timberwolves" => 3.7, "Pelicans" => 3.4, "Knicks" => 3.6, "Thunder" => 3.1, "Magic" => 2.9, "76ers" => 3.6, "Suns" => 3.9, "Trail Blazers" => 3.7, "Kings" => 3.2, "Spurs" => 3.4, "Raptors" => 2.8, "Jazz" => 4.0, "Wizards" => 3.4)
avg_3p_pct_per_player = Dict("Hawks" => 0.377, "Celtics" => 0.377, "Nets" => 0.337, "Hornets" => 0.381, "Bulls" => 0.353, "Cavaliers" => 0.361, "Mavericks" => 0.342, "Nuggets" => 0.396, "Pistons" => 0.363, "Warriors" => 0.355, "Rockets" => 0.362, "Pacers" => 0.359, "Clippers" => 0.365, "Lakers" => 0.355, "Grizzlies" => 0.356, "Heat" => 0.362, "Bucks" => 0.381, "Timberwolves" => 0.372, "Pelicans" => 0.348, "Knicks" => 0.375, "Thunder" => 0.361, "Magic" => 0.339, "76ers" => 0.352, "Suns" => 0.351, "Trail Blazers" => 0.345, "Kings" => 0.341, "Spurs" => 0.360, "Raptors" => 0.353, "Jazz" => 0.351, "Wizards" => 0.358)
avg_2ps_made_per_game_per_player = Dict("Hawks" => 2.7, "Celtics" => 2.6, "Nets" => 2.3, "Hornets" => 2.1, "Bulls" => 2.6, "Cavaliers" => 2.6, "Mavericks" => 2.8, "Nuggets" => 3.0, "Pistons" => 2.8, "Warriors" => 2.3, "Rockets" => 2.8, "Pacers" => 2.4, "Clippers" => 2.7, "Lakers" => 2.9, "Grizzlies" => 2.6, "Heat" => 2.8, "Bucks" => 2.6, "Timberwolves" => 2.8, "Pelicans" => 2.8, "Knicks" => 2.5, "Thunder" => 2.6, "Magic" => 2.6, "76ers" => 3.1, "Suns" => 2.5, "Trail Blazers" => 2.5, "Kings" => 3.1, "Spurs" => 2.6, "Raptors" => 2.9, "Jazz" => 3.1, "Wizards" => 2.9)
avg_2ps_attempted_per_game_per_player = Dict("Hawks" => 5.0, "Celtics" => 4.7, "Nets" => 4.4, "Hornets" => 3.9, "Bulls" => 4.7, "Cavaliers" => 4.4, "Mavericks" => 5.2, "Nuggets" => 5.3, "Pistons" => 5.1, "Warriors" => 4.1, "Rockets" => 5.2, "Pacers" => 4.4, "Clippers" => 4.7, "Lakers" => 4.9, "Grizzlies" => 4.7, "Heat" => 5.2, "Bucks" => 4.6, "Timberwolves" => 5.0, "Pelicans" => 5.4, "Knicks" => 4.5, "Thunder" => 4.6, "Magic" => 4.8, "76ers" => 5.8, "Suns" => 4.8, "Trail Blazers" => 4.5, "Kings" => 5.7, "Spurs" => 4.6, "Raptors" => 5.1, "Jazz" => 5.6, "Wizards" => 5.4)
avg_2p_pct_per_player = Dict("Hawks" => 0.553, "Celtics" => 0.558, "Nets" => 0.527, "Hornets" => 0.539, "Bulls" => 0.556, "Cavaliers" => 0.591, "Mavericks" => 0.534, "Nuggets" => 0.570, "Pistons" => 0.551, "Warriors" => 0.567, "Rockets" => 0.539, "Pacers" => 0.533, "Clippers" => 0.573, "Lakers" => 0.595, "Grizzlies" => 0.548, "Heat" => 0.542, "Bucks" => 0.561, "Timberwolves" => 0.567, "Pelicans" => 0.530, "Knicks" => 0.554, "Thunder" => 0.570, "Magic" => 0.539, "76ers" => 0.532, "Suns" => 0.532, "Trail Blazers" => 0.550, "Kings" => 0.538, "Spurs" => 0.574, "Raptors" => 0.568, "Jazz" => 0.547, "Wizards" => 0.535)
avg_efg_pct_per_player = Dict("Hawks" => 0.567, "Celtics" => 0.583, "Nets" => 0.511, "Hornets" => 0.568, "Bulls" => 0.537, "Cavaliers" => 0.548, "Mavericks" => 0.545, "Nuggets" => 0.571, "Pistons" => 0.540, "Warriors" => 0.554, "Rockets" => 0.524, "Pacers" => 0.537, "Clippers" => 0.559, "Lakers" => 0.568, "Grizzlies" => 0.545, "Heat" => 0.543, "Bucks" => 0.561, "Timberwolves" => 0.565, "Pelicans" => 0.527, "Knicks" => 0.564, "Thunder" => 0.546, "Magic" => 0.528, "76ers" => 0.536, "Suns" => 0.537, "Trail Blazers" => 0.526, "Kings" => 0.534, "Spurs" => 0.556, "Raptors" => 0.560, "Jazz" => 0.536, "Wizards" => 0.545)
avg_fts_made_per_game_per_player = Dict("Hawks" => 1.5, "Celtics" => 1.5, "Nets" => 1.7, "Hornets" => 1.5, "Bulls" => 1.4, "Cavaliers" => 1.6, "Mavericks" => 1.8, "Nuggets" => 2.1, "Pistons" => 1.7, "Warriors" => 1.7, "Rockets" => 1.6, "Pacers" => 1.4, "Clippers" => 2.0, "Lakers" => 2.0, "Grizzlies" => 1.6, "Heat" => 1.9, "Bucks" => 1.4, "Timberwolves" => 1.9, "Pelicans" => 1.9, "Knicks" => 1.5, "Thunder" => 1.7, "Magic" => 2.0, "76ers" => 2.2, "Suns" => 1.5, "Trail Blazers" => 1.8, "Kings" => 1.8, "Spurs" => 1.7, "Raptors" => 1.6, "Jazz" => 2.2, "Wizards" => 1.6)
avg_fts_attempted_per_game_per_player = Dict("Hawks" => 1.9, "Celtics" => 1.8, "Nets" => 2.2, "Hornets" => 1.9, "Bulls" => 1.8, "Cavaliers" => 2.1, "Mavericks" => 2.4, "Nuggets" => 2.6, "Pistons" => 2.3, "Warriors" => 2.0, "Rockets" => 2.0, "Pacers" => 1.9, "Clippers" => 2.4, "Lakers" => 2.7, "Grizzlies" => 2.1, "Heat" => 2.4, "Bucks" => 2.0, "Timberwolves" => 2.6, "Pelicans" => 2.4, "Knicks" => 1.9, "Thunder" => 2.1, "Magic" => 2.4, "76ers" => 2.7, "Suns" => 2.0, "Trail Blazers" => 2.3, "Kings" => 2.3, "Spurs" => 2.2, "Raptors" => 2.1, "Jazz" => 2.7, "Wizards" => 2.1)
avg_ft_pct_per_player = Dict("Hawks" => 0.779, "Celtics" => 0.805, "Nets" => 0.775, "Hornets" => 0.811, "Bulls" => 0.767, "Cavaliers" => 0.762, "Mavericks" => 0.731, "Nuggets" => 0.805, "Pistons" => 0.765, "Warriors" => 0.818, "Rockets" => 0.759, "Pacers" => 0.759, "Clippers" => 0.824, "Lakers" => 0.758, "Grizzlies" => 0.770, "Heat" => 0.796, "Bucks" => 0.718, "Timberwolves" => 0.792, "Pelicans" => 0.793, "Knicks" => 0.798, "Thunder" => 0.819, "Magic" => 0.801, "76ers" => 0.814, "Suns" => 0.785, "Trail Blazers" => 0.766, "Kings" => 0.773, "Spurs" => 0.787, "Raptors" => 0.755, "Jazz" => 0.802, "Wizards" => 0.769)
avg_orb_per_game_per_player = Dict("Hawks" => 1.0, "Celtics" => 1.2, "Nets" => 1.0, "Hornets" => 1.1, "Bulls" => 1.0, "Cavaliers" => 1.1, "Mavericks" => 1.0, "Nuggets" => 1.0, "Pistons" => 1.1, "Warriors" => 1.0, "Rockets" => 1.5, "Pacers" => 0.9, "Clippers" => 1.0, "Lakers" => 0.9, "Grizzlies" => 1.1, "Heat" => 1.1, "Bucks" => 0.9, "Timberwolves" => 1.1, "Pelicans" => 1.1, "Knicks" => 1.2, "Thunder" => 0.9, "Magic" => 1.0, "76ers" => 1.2, "Suns" => 1.1, "Trail Blazers" => 1.2, "Kings" => 1.1, "Spurs" => 1.0, "Raptors" => 1.1, "Jazz" => 1.1, "Wizards" => 1.1)
avg_drb_per_game_per_player = Dict("Hawks" => 3.0, "Celtics" => 3.2, "Nets" => 2.8, "Hornets" => 2.9, "Bulls" => 3.2, "Cavaliers" => 3.1, "Mavericks" => 3.1, "Nuggets" => 3.5, "Pistons" => 2.8, "Warriors" => 2.8, "Rockets" => 3.1, "Pacers" => 2.7, "Clippers" => 3.0, "Lakers" => 3.0, "Grizzlies" => 3.0, "Heat" => 3.2, "Bucks" => 3.0, "Timberwolves" => 3.1, "Pelicans" => 2.9, "Knicks" => 3.0, "Thunder" => 3.1, "Magic" => 2.8, "76ers" => 3.3, "Suns" => 2.7, "Trail Blazers" => 2.8, "Kings" => 2.9, "Spurs" => 3.2, "Raptors" => 2.9, "Jazz" => 3.4, "Wizards" => 3.0)
avg_trb_per_game_per_player = Dict("Hawks" => 4.0, "Celtics" => 4.4, "Nets" => 3.8, "Hornets" => 4.0, "Bulls" => 4.2, "Cavaliers" => 4.3, "Mavericks" => 4.1, "Nuggets" => 4.5, "Pistons" => 3.9, "Warriors" => 3.8, "Rockets" => 4.6, "Pacers" => 3.6, "Clippers" => 4.0, "Lakers" => 3.8, "Grizzlies" => 4.1, "Heat" => 4.2, "Bucks" => 3.9, "Timberwolves" => 4.2, "Pelicans" => 3.9, "Knicks" => 4.2, "Thunder" => 4.0, "Magic" => 3.8, "76ers" => 4.5, "Suns" => 3.9, "Trail Blazers" => 4.1, "Kings" => 4.0, "Spurs" => 4.1, "Raptors" => 3.9, "Jazz" => 4.5, "Wizards" => 4.0)
avg_assists_per_game_per_player = Dict("Hawks" => 2.9, "Celtics" => 2.4, "Nets" => 2.4, "Hornets" => 2.2, "Bulls" => 2.8, "Cavaliers" => 2.3, "Mavericks" => 2.2, "Nuggets" => 2.9, "Pistons" => 2.5, "Warriors" => 2.7, "Rockets" => 2.2, "Pacers" => 2.5, "Clippers" => 4.5, "Lakers" => 2.5, "Grizzlies" => 2.6, "Heat" => 2.7, "Bucks" => 2.6, "Timberwolves" => 2.4, "Pelicans" => 2.4, "Knicks" => 2.4, "Thunder" => 2.3, "Magic" => 2.3, "76ers" => 2.5, "Suns" => 2.3, "Trail Blazers" => 2.3, "Kings" => 2.5, "Spurs" => 2.5, "Raptors" => 2.6, "Jazz" => 3.0, "Wizards" => 2.5)
avg_steals_per_game_per_player = Dict("Hawks" => 0.9, "Celtics" => 0.7, "Nets" => 0.8, "Hornets" => 0.6, "Bulls" => 0.7, "Cavaliers" => 0.8, "Mavericks" => 0.7, "Nuggets" => 0.7, "Pistons" => 0.9, "Warriors" => 0.9, "Rockets" => 0.8, "Pacers" => 0.7, "Clippers" => 2.1, "Lakers" => 0.8, "Grizzlies" => 0.8, "Heat" => 0.8, "Bucks" => 0.7, "Timberwolves" => 0.8, "Pelicans" => 0.8, "Knicks" => 0.7, "Thunder" => 0.9, "Magic" => 0.7, "76ers" => 0.9, "Suns" => 0.9, "Trail Blazers" => 0.7, "Kings" => 0.8, "Spurs" => 0.7, "Raptors" => 0.8, "Jazz" => 0.8, "Wizards" => 0.8)
avg_blocks_per_game_per_player = Dict("Hawks" => 0.4, "Celtics" => 0.5, "Nets" => 0.4, "Hornets" => 0.4, "Bulls" => 0.5, "Cavaliers" => 0.4, "Mavericks" => 0.5, "Nuggets" => 0.4, "Pistons" => 0.6, "Warriors" => 0.4, "Rockets" => 0.5, "Pacers" => 0.4, "Clippers" => 0.8, "Lakers" => 0.4, "Grizzlies" => 0.5, "Heat" => 0.4, "Bucks" => 0.4, "Timberwolves" => 0.6, "Pelicans" => 0.5, "Knicks" => 0.4, "Thunder" => 0.5, "Magic" => 0.4, "76ers" => 0.6, "Suns" => 0.4, "Trail Blazers" => 0.5, "Kings" => 0.5, "Spurs" => 0.5, "Raptors" => 0.4, "Jazz" => 0.4, "Wizards" => 0.6)
avg_turnovers_per_game_per_player = Dict("Hawks" => 1.3, "Celtics" => 1.1, "Nets" => 1.5, "Hornets" => 1.2, "Bulls" => 1.3, "Cavaliers" => 1.2, "Mavericks" => 1.3, "Nuggets" => 1.2, "Pistons" => 1.3, "Warriors" => 1.4,  "Rockets" => 1.3, "Pacers" => 1.2, "Clippers" => 1.2, "Lakers" => 1.4, "Grizzlies" => 1.4, "Heat" => 1.2, "Bucks" => 1.4, "Timberwolves" => 1.3, "Pelicans" => 1.2, "Knicks" => 1.1, "Thunder" => 1.1, "Magic" => 1.2, "76ers" => 1.4, "Suns" => 1.3, "Trail Blazers" => 1.5, "Kings" => 1.4, "Spurs" => 1.1, "Raptors" => 1.1, "Jazz" => 1.6, "Wizards" => 1.5)
avg_fouls_per_game_per_player = Dict("Hawks" => 1.9, "Celtics" => 1.9, "Nets" => 2.0, "Hornets" => 1.7, "Bulls" => 1.8, "Cavaliers" => 1.8, "Mavericks" => 1.7, "Nuggets" => 1.9, "Pistons" => 1.9, "Warriors" => 1.7, "Rockets" => 1.7, "Pacers" => 1.9, "Clippers" => 1.7, "Lakers" => 1.7, "Grizzlies" => 1.9, "Heat" => 1.8, "Bucks" => 1.8, "Timberwolves" => 2.0, "Pelicans" => 2.0, "Knicks" => 1.8, "Thunder" => 1.7, "Magic" => 1.8, "76ers" => 2.1, "Suns" => 1.8, "Trail Blazers" => 1.7, "Kings" => 2.0, "Spurs" => 1.6, "Raptors" => 2.0, "Jazz" => 2.1, "Wizards" => 2.1)
avg_points_per_game_per_player = Dict("Hawks" => 11.5, "Celtics" => 11.3, "Nets" => 10.0, "Hornets" => 10.1, "Bulls" => 10.4, "Cavaliers" => 10.6, "Mavericks" => 10.2, "Nuggets" => 12.3, "Pistons" => 10.3, "Warriors" => 10.8,  "Rockets" => 10.2, "Pacers" => 9.5, "Clippers" => 10.7, "Lakers" => 11.3, "Grizzlies" => 10.7, "Heat" => 11.5, "Bucks" => 10.2, "Timberwolves" => 11.6, "Pelicans" => 11.2, "Knicks" => 10.6, "Thunder" => 10.3, "Magic" => 10.1, "76ers" => 12.2, "Suns" => 10.8, "Trail Blazers" => 10.4, "Kings" => 11.2, "Spurs" => 10.7, "Raptors" => 10.4, "Jazz" => 12.5, "Wizards" => 11.0)
avg_per_per_player = Dict("Hawks" => 14.2, "Celtics" => 15.7, "Nets" => 12.1, "Hornets" => 14.7, "Bulls" => 13.4, "Cavaliers" => 214.7, "Mavericks" => 13.7, "Nuggets" => 15.5, "Pistons" => 15.1, "Warriors" => 15.1,  "Rockets" => 14.0, "Pacers" => 13.2, "Clippers" => 14.8, "Lakers" => 14.4, "Grizzlies" => 14.1, "Heat" => 15.0, "Bucks" => 13.9, "Timberwolves" => 15.2, "Pelicans" => 13.8, "Knicks" => 14.7, "Thunder" => 15.5, "Magic" => 14.1, "76ers" => 15.0, "Suns" => 14.3, "Trail Blazers" => 13.3, "Kings" => 13.9, "Spurs" => 15.2, "Raptors" => 14.4, "Jazz" => 14.3, "Wizards" => 14.3)
avg_ws_per_player = Dict("Hawks" => 3.8, "Celtics" => 5.2, "Nets" => 1.1, "Hornets" => 2.6, "Bulls" => 2.2, "Cavaliers" => 3.5, "Mavericks" => 2.1, "Nuggets" => 4.1, "Pistons" => 4.2, "Warriors" => 2.6, "Rockets" => 4.2, "Pacers" => 1.5, "Clippers" => 3.4, "Lakers" => 3.4, "Grizzlies" => 1.9, "Heat" => 3.3, "Bucks" => 1.8, "Timberwolves" => 4.2, "Pelicans" => 2.4, "Knicks" => 4.4, "Thunder" => 4.3, "Magic" => 2.8, "76ers" => 3.3, "Suns" => 3.2, "Trail Blazers" => 2.8, "Kings" => 1.7, "Spurs" => 4.5, "Raptors" => 3.7, "Jazz" => 1.5, "Wizards" => 1.2)

teams = collect(keys(team_wins))

team_wins_values = [team_wins[team] for team in teams]

avg_g_played_values = [avg_g_played[team] for team in teams]
avg_mins_played_per_game_per_player_values = [avg_mins_played_per_game_per_player[team] for team in teams]
avg_fgs_made_per_game_per_player_values = [avg_fgs_made_per_game_per_player[team] for team in teams]
avg_fgs_attempted_per_game_per_player_values = [avg_fgs_attempted_per_game_per_player[team] for team in teams]
avg_fg_pct_per_game_per_player_values = [avg_fg_pct_per_player[team] for team in teams]
avg_3ps_made_per_game_per_player_values = [avg_3ps_made_per_game_per_player[team] for team in teams]
avg_3ps_attempted_per_game_per_player_values = [avg_3ps_attempted_per_game_per_player[team] for team in teams]
avg_3p_pct_per_game_per_player_values = [avg_3p_pct_per_player[team] for team in teams]
avg_2ps_made_per_game_per_player_values = [avg_2ps_made_per_game_per_player[team] for team in teams]
avg_2ps_attempted_per_game_per_player_values = [avg_2ps_attempted_per_game_per_player[team] for team in teams]
avg_2p_pct_per_game_per_player_values = [avg_2p_pct_per_player[team] for team in teams]
avg_efg_pct_per_player_values = [avg_efg_pct_per_player[team] for team in teams]
avg_fts_made_per_game_per_player_values = [avg_fts_made_per_game_per_player[team] for team in teams]
avg_fts_attempted_per_game_per_player_values = [avg_fts_attempted_per_game_per_player[team] for team in teams]
avg_ft_pct_per_game_per_player_values = [avg_ft_pct_per_player[team] for team in teams]
avg_orb_per_game_per_player_values = [avg_orb_per_game_per_player[team] for team in teams]
avg_drb_per_game_per_player_values = [avg_drb_per_game_per_player[team] for team in teams]
avg_trb_per_game_per_player_values = [avg_trb_per_game_per_player[team] for team in teams]
avg_assists_per_game_per_player_values = [avg_assists_per_game_per_player[team] for team in teams]
avg_steals_per_game_per_player_values = [avg_steals_per_game_per_player[team] for team in teams]
avg_blocks_per_game_per_player_values = [avg_blocks_per_game_per_player[team] for team in teams]
avg_turnovers_per_game_per_player_values = [avg_turnovers_per_game_per_player[team] for team in teams]
avg_fouls_per_game_per_player_values = [avg_fouls_per_game_per_player[team] for team in teams]
avg_points_per_game_per_player_values = [avg_points_per_game_per_player[team] for team in teams]
avg_per_per_player_values = [avg_per_per_player[team] for team in teams]
avg_ws_per_player_values = [avg_ws_per_player[team] for team in teams]

games_played_r = cor(team_wins_values, avg_g_played_values)
mins_played_r = cor(team_wins_values, avg_mins_played_per_game_per_player_values)
fgs_made_r = cor(team_wins_values, avg_fgs_made_per_game_per_player_values)
fgs_attempted_r = cor(team_wins_values, avg_fgs_attempted_per_game_per_player_values)
fg_pct_r = cor(team_wins_values, avg_fg_pct_per_game_per_player_values)
threepoints_made_r = cor(team_wins_values, avg_3ps_made_per_game_per_player_values)
threepoints_attempted_r = cor(team_wins_values, avg_3ps_attempted_per_game_per_player_values)
threepoint_pct_r = cor(team_wins_values, avg_3p_pct_per_game_per_player_values)
twopoints_made_r = cor(team_wins_values, avg_2ps_made_per_game_per_player_values)
twopoints_attempted_r = cor(team_wins_values, avg_2ps_attempted_per_game_per_player_values)
twopoint_pct_r = cor(team_wins_values, avg_2p_pct_per_game_per_player_values)
efg_pct_r = cor(team_wins_values, avg_efg_pct_per_player_values)
fts_made_r = cor(team_wins_values, avg_fts_made_per_game_per_player_values)
fts_attempted_r = cor(team_wins_values, avg_fts_attempted_per_game_per_player_values)
ft_pct_r = cor(team_wins_values, avg_ft_pct_per_game_per_player_values)
orb_r = cor(team_wins_values, avg_orb_per_game_per_player_values)
drb_r = cor(team_wins_values, avg_drb_per_game_per_player_values)
trb_r = cor(team_wins_values, avg_trb_per_game_per_player_values)
assists_r = cor(team_wins_values, avg_assists_per_game_per_player_values)
steals_r = cor(team_wins_values, avg_steals_per_game_per_player_values)
blocks_r = cor(team_wins_values, avg_blocks_per_game_per_player_values)
turnovers_r = cor(team_wins_values, avg_turnovers_per_game_per_player_values)
fouls_r = cor(team_wins_values, avg_fouls_per_game_per_player_values)
ppg_r = cor(team_wins_values, avg_points_per_game_per_player_values)
per_r = cor(team_wins_values, avg_per_per_player_values)
ws_r = cor(team_wins_values, avg_ws_per_player_values)

println("Correlation between team wins and average games played: ", round(games_played_r, digits=3))
println("Correlation between team wins and average minutes played per player: ", round(mins_played_r, digits=3))
println("Correlation between team wins and average FGS made per game per player: ", round(fgs_made_r, digits=3))
println("Correlation between team wins and average FGS attempted per game per player: ", round(fgs_attempted_r, digits=3))
println("Correlation between team wins and average FG percent per game per player: ", round(fg_pct_r, digits=3))
println("Correlation between team wins and average 3PS made per game per player: ", round(threepoints_made_r, digits=3))
println("Correlation between team wins and average 3PS attempted per game per player: ", round(threepoints_attempted_r, digits=3))
println("Correlation between team wins and average 3P percent per game per player: ", round(threepoint_pct_r, digits=3))
println("Correlation between team wins and average 2PS made per game per player: ", round(twopoints_made_r, digits=3))
println("Correlation between team wins and average 2PS attempted per game per player: ", round(twopoints_attempted_r, digits=3))
println("Correlation between team wins and average 2P percent per game per player: ", round(twopoint_pct_r, digits=3))
println("Correlation between team wins and average EFG percent per game per player: ", round(efg_pct_r, digits=3))
println("Correlation between team wins and average FTS made per game per player: ", round(fts_made_r, digits=3))
println("Correlation between team wins and average FTS attempted per game per player: ", round(fts_attempted_r, digits=3))
println("Correlation between team wins and average FT percent per game per player: ", round(ft_pct_r, digits=3))
println("Correlation between team wins and average ORB per game per player: ", round(orb_r, digits=3))
println("Correlation between team wins and average DRB per game per player: ", round(drb_r, digits=3))
println("Correlation between team wins and average TRB per game per player: ", round(trb_r, digits=3))
println("Correlation between team wins and average assists per game per player: ", round(assists_r, digits=3))
println("Correlation between team wins and average steals per game per player: ", round(steals_r, digits=3))
println("Correlation between team wins and average blocks per game per player: ", round(blocks_r, digits=3))
println("Correlation between team wins and average turnovers per game per player: ", round(turnovers_r, digits=3))
println("Correlation between team wins and average fouls per game per player: ", round(fouls_r, digits=3))
println("Correlation between team wins and average PPG per game per player: ", round(ppg_r, digits=3))
println("Correlation between team wins and average PER per game per player: ", round(per_r, digits=3))
println("Correlation between team wins and average WS per game per player: ", round(ws_r, digits=3))